.TH x0vncserver 1 "03 Mar 2005" "RealVNC Ltd" "Virtual Network Computing"
.SH NAME
x0vncserver \- VNC server which continuously polls an X display
.SH SYNOPSIS
.B x0vncserver
[\fIparameters\fP]
.SH DESCRIPTION
.B x0vncserver
is a VNC server which continuously polls any X display, allowing it to be
controlled via VNC.  How usable it will be depends a lot on the machine it's
running on, and what you're expecting.  It won't be as fast as Xvnc or a native
X server with VNC support compiled in, but in many cases it is the best option
since it is just an ordinary X application requiring no special installation.

It has many of the same parameters as Xvnc.  Running \fBx0vncserver -h\fP will
give a list of parameters with descriptions.  Note that you need to explicitly
specify an appropriate password file using the PasswordFile parameter.

.SH SEE ALSO
.BR Xvnc (1)
.BR vncpasswd (1),
.BR vncviewer (1),
.BR vncserver (1),
.br
http://www.realvnc.com

.SH AUTHOR
Tristan Richardson, RealVNC Ltd.

VNC was originally developed by the RealVNC team while at Olivetti Research Ltd
/ AT&T Laboratories Cambridge.  It is now being maintained by RealVNC Ltd.  See
http://www.realvnc.com for details.
