var annotated_dup =
[
    [ "deskflow", "namespacedeskflow.html", [
      [ "client", "namespacedeskflow_1_1client.html", [
        [ "HelloBack", "classdeskflow_1_1client_1_1HelloBack.html", "classdeskflow_1_1client_1_1HelloBack" ]
      ] ],
      [ "core", "namespacedeskflow_1_1core.html", [
        [ "ipc", "namespacedeskflow_1_1core_1_1ipc.html", [
          [ "DaemonIpcServer", "classdeskflow_1_1core_1_1ipc_1_1DaemonIpcServer.html", "classdeskflow_1_1core_1_1ipc_1_1DaemonIpcServer" ]
        ] ]
      ] ],
      [ "gui", "namespacedeskflow_1_1gui.html", [
        [ "core", "namespacedeskflow_1_1gui_1_1core.html", [
          [ "WaylandWarnings", "classdeskflow_1_1gui_1_1core_1_1WaylandWarnings.html", "classdeskflow_1_1gui_1_1core_1_1WaylandWarnings" ]
        ] ],
        [ "ipc", "namespacedeskflow_1_1gui_1_1ipc.html", [
          [ "DaemonIpcClient", "classdeskflow_1_1gui_1_1ipc_1_1DaemonIpcClient.html", "classdeskflow_1_1gui_1_1ipc_1_1DaemonIpcClient" ]
        ] ],
        [ "messages", "namespacedeskflow_1_1gui_1_1messages.html", [
          [ "Errors", "structdeskflow_1_1gui_1_1messages_1_1Errors.html", "structdeskflow_1_1gui_1_1messages_1_1Errors" ]
        ] ],
        [ "proxy", "namespacedeskflow_1_1gui_1_1proxy.html", [
          [ "QProcessProxy", "classdeskflow_1_1gui_1_1proxy_1_1QProcessProxy.html", "classdeskflow_1_1gui_1_1proxy_1_1QProcessProxy" ]
        ] ],
        [ "ClientConnection", "classdeskflow_1_1gui_1_1ClientConnection.html", "classdeskflow_1_1gui_1_1ClientConnection" ],
        [ "CoreProcess", "classdeskflow_1_1gui_1_1CoreProcess.html", "classdeskflow_1_1gui_1_1CoreProcess" ],
        [ "FileTail", "classdeskflow_1_1gui_1_1FileTail.html", "classdeskflow_1_1gui_1_1FileTail" ],
        [ "IServerConfig", "classdeskflow_1_1gui_1_1IServerConfig.html", "classdeskflow_1_1gui_1_1IServerConfig" ],
        [ "Logger", "classdeskflow_1_1gui_1_1Logger.html", "classdeskflow_1_1gui_1_1Logger" ],
        [ "ServerConnection", "classdeskflow_1_1gui_1_1ServerConnection.html", "classdeskflow_1_1gui_1_1ServerConnection" ],
        [ "ServerMessage", "classdeskflow_1_1gui_1_1ServerMessage.html", "classdeskflow_1_1gui_1_1ServerMessage" ],
        [ "TlsUtility", "classdeskflow_1_1gui_1_1TlsUtility.html", "classdeskflow_1_1gui_1_1TlsUtility" ]
      ] ],
      [ "languages", "namespacedeskflow_1_1languages.html", [
        [ "LanguageManager", "classdeskflow_1_1languages_1_1LanguageManager.html", "classdeskflow_1_1languages_1_1LanguageManager" ]
      ] ],
      [ "platform", "namespacedeskflow_1_1platform.html", [
        [ "MSWindowsProcess", "classdeskflow_1_1platform_1_1MSWindowsProcess.html", "classdeskflow_1_1platform_1_1MSWindowsProcess" ]
      ] ],
      [ "server", "namespacedeskflow_1_1server.html", [
        [ "Config", "classdeskflow_1_1server_1_1Config.html", "classdeskflow_1_1server_1_1Config" ],
        [ "ConfigReadContext", "classdeskflow_1_1server_1_1ConfigReadContext.html", "classdeskflow_1_1server_1_1ConfigReadContext" ],
        [ "XConfigRead", "classdeskflow_1_1server_1_1XConfigRead.html", "classdeskflow_1_1server_1_1XConfigRead" ]
      ] ],
      [ "string", "namespacedeskflow_1_1string.html", [
        [ "CaselessCmp", "classdeskflow_1_1string_1_1CaselessCmp.html", "classdeskflow_1_1string_1_1CaselessCmp" ]
      ] ],
      [ "ArgsBase", "classdeskflow_1_1ArgsBase.html", "classdeskflow_1_1ArgsBase" ],
      [ "ClientArgs", "classdeskflow_1_1ClientArgs.html", "classdeskflow_1_1ClientArgs" ],
      [ "Config", "classdeskflow_1_1Config.html", "classdeskflow_1_1Config" ],
      [ "EiEventQueueBuffer", "classdeskflow_1_1EiEventQueueBuffer.html", "classdeskflow_1_1EiEventQueueBuffer" ],
      [ "EiKeyState", "classdeskflow_1_1EiKeyState.html", "classdeskflow_1_1EiKeyState" ],
      [ "EiScreen", "classdeskflow_1_1EiScreen.html", "classdeskflow_1_1EiScreen" ],
      [ "FinalAction", "classdeskflow_1_1FinalAction.html", "classdeskflow_1_1FinalAction" ],
      [ "IStream", "classdeskflow_1_1IStream.html", "classdeskflow_1_1IStream" ],
      [ "KeyMap", "classdeskflow_1_1KeyMap.html", "classdeskflow_1_1KeyMap" ],
      [ "PortalInputCapture", "classdeskflow_1_1PortalInputCapture.html", "classdeskflow_1_1PortalInputCapture" ],
      [ "PortalRemoteDesktop", "classdeskflow_1_1PortalRemoteDesktop.html", "classdeskflow_1_1PortalRemoteDesktop" ],
      [ "Screen", "classdeskflow_1_1Screen.html", "classdeskflow_1_1Screen" ],
      [ "ServerArgs", "classdeskflow_1_1ServerArgs.html", "classdeskflow_1_1ServerArgs" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "iterator_traits< deskflow::server::Config >", "structstd_1_1iterator__traits_3_01deskflow_1_1server_1_1Config_01_4.html", "structstd_1_1iterator__traits_3_01deskflow_1_1server_1_1Config_01_4" ]
    ] ],
    [ "validators", "namespacevalidators.html", [
      [ "AliasValidator", "classvalidators_1_1AliasValidator.html", "classvalidators_1_1AliasValidator" ],
      [ "ComputerNameValidator", "classvalidators_1_1ComputerNameValidator.html", "classvalidators_1_1ComputerNameValidator" ],
      [ "EmptyStringValidator", "classvalidators_1_1EmptyStringValidator.html", "classvalidators_1_1EmptyStringValidator" ],
      [ "IStringValidator", "classvalidators_1_1IStringValidator.html", "classvalidators_1_1IStringValidator" ],
      [ "LineEditValidator", "classvalidators_1_1LineEditValidator.html", "classvalidators_1_1LineEditValidator" ],
      [ "ScreenDuplicationsValidator", "classvalidators_1_1ScreenDuplicationsValidator.html", "classvalidators_1_1ScreenDuplicationsValidator" ],
      [ "ScreenNameValidator", "classvalidators_1_1ScreenNameValidator.html", "classvalidators_1_1ScreenNameValidator" ],
      [ "SpacesValidator", "classvalidators_1_1SpacesValidator.html", "classvalidators_1_1SpacesValidator" ],
      [ "ValidationError", "classvalidators_1_1ValidationError.html", "classvalidators_1_1ValidationError" ]
    ] ],
    [ "AboutDialog", "classAboutDialog.html", "classAboutDialog" ],
    [ "Action", "classAction.html", "classAction" ],
    [ "ActionDialog", "classActionDialog.html", "classActionDialog" ],
    [ "AddClientDialog", "classAddClientDialog.html", "classAddClientDialog" ],
    [ "App", "classApp.html", "classApp" ],
    [ "AppUtil", "classAppUtil.html", "classAppUtil" ],
    [ "AppUtilUnix", "classAppUtilUnix.html", "classAppUtilUnix" ],
    [ "AppUtilWindows", "classAppUtilWindows.html", "classAppUtilWindows" ],
    [ "Arch", "classArch.html", "classArch" ],
    [ "ArchCondImpl", "classArchCondImpl.html", "classArchCondImpl" ],
    [ "ArchDaemonNone", "classArchDaemonNone.html", "classArchDaemonNone" ],
    [ "ArchDaemonUnix", "classArchDaemonUnix.html", "classArchDaemonUnix" ],
    [ "ArchDaemonWindows", "classArchDaemonWindows.html", "classArchDaemonWindows" ],
    [ "ArchLogUnix", "classArchLogUnix.html", "classArchLogUnix" ],
    [ "ArchLogWindows", "classArchLogWindows.html", "classArchLogWindows" ],
    [ "ArchMiscWindows", "classArchMiscWindows.html", "classArchMiscWindows" ],
    [ "ArchMultithreadPosix", "classArchMultithreadPosix.html", "classArchMultithreadPosix" ],
    [ "ArchMultithreadWindows", "classArchMultithreadWindows.html", "classArchMultithreadWindows" ],
    [ "ArchMutexImpl", "classArchMutexImpl.html", "classArchMutexImpl" ],
    [ "ArchMutexLock", "classArchMutexLock.html", "classArchMutexLock" ],
    [ "ArchNetAddressImpl", "classArchNetAddressImpl.html", "classArchNetAddressImpl" ],
    [ "ArchNetworkBSD", "classArchNetworkBSD.html", "classArchNetworkBSD" ],
    [ "ArchNetworkWinsock", "classArchNetworkWinsock.html", "classArchNetworkWinsock" ],
    [ "ArchSocketImpl", "classArchSocketImpl.html", "classArchSocketImpl" ],
    [ "ArchString", "classArchString.html", "classArchString" ],
    [ "ArchThreadImpl", "classArchThreadImpl.html", "classArchThreadImpl" ],
    [ "ArgParser", "classArgParser.html", "classArgParser" ],
    [ "BaseClientProxy", "classBaseClientProxy.html", "classBaseClientProxy" ],
    [ "CBMPHeader", "structCBMPHeader.html", "structCBMPHeader" ],
    [ "CBMPInfoHeader", "structCBMPInfoHeader.html", "structCBMPInfoHeader" ],
    [ "Chunk", "classChunk.html", "classChunk" ],
    [ "ChunkType", "structChunkType.html", "structChunkType" ],
    [ "Client", "classClient.html", "classClient" ],
    [ "ClientApp", "classClientApp.html", "classClientApp" ],
    [ "ClientInfo", "classClientInfo.html", "classClientInfo" ],
    [ "ClientListener", "classClientListener.html", "classClientListener" ],
    [ "ClientProxy", "classClientProxy.html", "classClientProxy" ],
    [ "ClientProxy1_0", "classClientProxy1__0.html", "classClientProxy1__0" ],
    [ "ClientProxy1_1", "classClientProxy1__1.html", "classClientProxy1__1" ],
    [ "ClientProxy1_2", "classClientProxy1__2.html", "classClientProxy1__2" ],
    [ "ClientProxy1_3", "classClientProxy1__3.html", "classClientProxy1__3" ],
    [ "ClientProxy1_4", "classClientProxy1__4.html", "classClientProxy1__4" ],
    [ "ClientProxy1_5", "classClientProxy1__5.html", "classClientProxy1__5" ],
    [ "ClientProxy1_6", "classClientProxy1__6.html", "classClientProxy1__6" ],
    [ "ClientProxy1_7", "classClientProxy1__7.html", "classClientProxy1__7" ],
    [ "ClientProxy1_8", "classClientProxy1__8.html", "classClientProxy1__8" ],
    [ "ClientProxyUnknown", "classClientProxyUnknown.html", "classClientProxyUnknown" ],
    [ "Clipboard", "classClipboard.html", "classClipboard" ],
    [ "ClipboardChunk", "classClipboardChunk.html", "classClipboardChunk" ],
    [ "codepair", "structcodepair.html", "structcodepair" ],
    [ "CommandProcess", "classCommandProcess.html", "classCommandProcess" ],
    [ "CondVar", "classCondVar.html", "classCondVar" ],
    [ "CondVarBase", "classCondVarBase.html", "classCondVarBase" ],
    [ "ConsoleLogOutputter", "classConsoleLogOutputter.html", "classConsoleLogOutputter" ],
    [ "DaemonApp", "classDaemonApp.html", "classDaemonApp" ],
    [ "DataDownloader", "classDataDownloader.html", "classDataDownloader" ],
    [ "DisplayInvalidException", "classDisplayInvalidException.html", null ],
    [ "Event", "classEvent.html", "classEvent" ],
    [ "EventData", "classEventData.html", "classEventData" ],
    [ "EventQueue", "classEventQueue.html", "classEventQueue" ],
    [ "EventQueueTimer", "classEventQueueTimer.html", null ],
    [ "FileLogOutputter", "classFileLogOutputter.html", "classFileLogOutputter" ],
    [ "Fingerprint", "structFingerprint.html", "structFingerprint" ],
    [ "FingerprintDatabase", "classFingerprintDatabase.html", "classFingerprintDatabase" ],
    [ "FingerprintDialog", "classFingerprintDialog.html", "classFingerprintDialog" ],
    [ "FingerprintPreview", "classFingerprintPreview.html", "classFingerprintPreview" ],
    [ "FunctionEventJob", "classFunctionEventJob.html", "classFunctionEventJob" ],
    [ "FunctionJob", "classFunctionJob.html", "classFunctionJob" ],
    [ "Hotkey", "classHotkey.html", "classHotkey" ],
    [ "HotkeyDialog", "classHotkeyDialog.html", "classHotkeyDialog" ],
    [ "IApp", "classIApp.html", "classIApp" ],
    [ "IAppUtil", "classIAppUtil.html", "classIAppUtil" ],
    [ "IArchDaemon", "classIArchDaemon.html", "classIArchDaemon" ],
    [ "IArchLog", "classIArchLog.html", "classIArchLog" ],
    [ "IArchMultithread", "classIArchMultithread.html", "classIArchMultithread" ],
    [ "IArchNetwork", "classIArchNetwork.html", "classIArchNetwork" ],
    [ "IClient", "classIClient.html", "classIClient" ],
    [ "IClipboard", "classIClipboard.html", "classIClipboard" ],
    [ "IDataSocket", "classIDataSocket.html", "classIDataSocket" ],
    [ "IEventJob", "classIEventJob.html", "classIEventJob" ],
    [ "IEventQueue", "classIEventQueue.html", "classIEventQueue" ],
    [ "IEventQueueBuffer", "classIEventQueueBuffer.html", "classIEventQueueBuffer" ],
    [ "IInterface", "classIInterface.html", "classIInterface" ],
    [ "IJob", "classIJob.html", "classIJob" ],
    [ "IKeyState", "classIKeyState.html", "classIKeyState" ],
    [ "IListenSocket", "classIListenSocket.html", "classIListenSocket" ],
    [ "ILogOutputter", "classILogOutputter.html", "classILogOutputter" ],
    [ "IMSWindowsClipboardConverter", "classIMSWindowsClipboardConverter.html", "classIMSWindowsClipboardConverter" ],
    [ "IMSWindowsClipboardFacade", "classIMSWindowsClipboardFacade.html", "classIMSWindowsClipboardFacade" ],
    [ "INode", "classINode.html", null ],
    [ "InputFilter", "classInputFilter.html", "classInputFilter" ],
    [ "IOSXClipboardConverter", "classIOSXClipboardConverter.html", "classIOSXClipboardConverter" ],
    [ "IOSXKeyResource", "classIOSXKeyResource.html", "classIOSXKeyResource" ],
    [ "IPlatformScreen", "classIPlatformScreen.html", "classIPlatformScreen" ],
    [ "IPrimaryScreen", "classIPrimaryScreen.html", "classIPrimaryScreen" ],
    [ "IScreen", "classIScreen.html", "classIScreen" ],
    [ "IScreenSaver", "classIScreenSaver.html", "classIScreenSaver" ],
    [ "ISecondaryScreen", "classISecondaryScreen.html", "classISecondaryScreen" ],
    [ "ISocket", "classISocket.html", "classISocket" ],
    [ "ISocketFactory", "classISocketFactory.html", "classISocketFactory" ],
    [ "ISocketMultiplexerJob", "classISocketMultiplexerJob.html", "classISocketMultiplexerJob" ],
    [ "IXWindowsClipboardConverter", "classIXWindowsClipboardConverter.html", "classIXWindowsClipboardConverter" ],
    [ "KeyEntry", "structKeyEntry.html", "structKeyEntry" ],
    [ "KeyModifierNameMapEntry", "structKeyModifierNameMapEntry.html", "structKeyModifierNameMapEntry" ],
    [ "KeyNameMapEntry", "structKeyNameMapEntry.html", "structKeyNameMapEntry" ],
    [ "KeySequence", "classKeySequence.html", "classKeySequence" ],
    [ "KeySequenceWidget", "classKeySequenceWidget.html", "classKeySequenceWidget" ],
    [ "KeyState", "classKeyState.html", "classKeyState" ],
    [ "Lock", "classLock.html", "classLock" ],
    [ "Log", "classLog.html", "classLog" ],
    [ "MainWindow", "classMainWindow.html", "classMainWindow" ],
    [ "MSWindowsClipboard", "classMSWindowsClipboard.html", "classMSWindowsClipboard" ],
    [ "MSWindowsClipboardAnyTextConverter", "classMSWindowsClipboardAnyTextConverter.html", "classMSWindowsClipboardAnyTextConverter" ],
    [ "MSWindowsClipboardBitmapConverter", "classMSWindowsClipboardBitmapConverter.html", "classMSWindowsClipboardBitmapConverter" ],
    [ "MSWindowsClipboardFacade", "classMSWindowsClipboardFacade.html", "classMSWindowsClipboardFacade" ],
    [ "MSWindowsClipboardHTMLConverter", "classMSWindowsClipboardHTMLConverter.html", "classMSWindowsClipboardHTMLConverter" ],
    [ "MSWindowsClipboardTextConverter", "classMSWindowsClipboardTextConverter.html", "classMSWindowsClipboardTextConverter" ],
    [ "MSWindowsClipboardUTF16Converter", "classMSWindowsClipboardUTF16Converter.html", "classMSWindowsClipboardUTF16Converter" ],
    [ "MSWindowsDebugOutputter", "classMSWindowsDebugOutputter.html", "classMSWindowsDebugOutputter" ],
    [ "MSWindowsDesks", "classMSWindowsDesks.html", "classMSWindowsDesks" ],
    [ "MSWindowsEventQueueBuffer", "classMSWindowsEventQueueBuffer.html", "classMSWindowsEventQueueBuffer" ],
    [ "MSWindowsHandle", "classMSWindowsHandle.html", "classMSWindowsHandle" ],
    [ "MSWindowsHook", "classMSWindowsHook.html", "classMSWindowsHook" ],
    [ "MSWindowsKeyState", "classMSWindowsKeyState.html", "classMSWindowsKeyState" ],
    [ "MSWindowsPowerManager", "classMSWindowsPowerManager.html", "classMSWindowsPowerManager" ],
    [ "MSWindowsScreen", "classMSWindowsScreen.html", "classMSWindowsScreen" ],
    [ "MSWindowsScreenSaver", "classMSWindowsScreenSaver.html", "classMSWindowsScreenSaver" ],
    [ "MSWindowsSession", "classMSWindowsSession.html", "classMSWindowsSession" ],
    [ "MSWindowsWatchdog", "classMSWindowsWatchdog.html", "classMSWindowsWatchdog" ],
    [ "Mutex", "classMutex.html", "classMutex" ],
    [ "NetworkAddress", "classNetworkAddress.html", "classNetworkAddress" ],
    [ "NewScreenWidget", "classNewScreenWidget.html", "classNewScreenWidget" ],
    [ "OSXClipboard", "classOSXClipboard.html", "classOSXClipboard" ],
    [ "OSXClipboardAnyBitmapConverter", "classOSXClipboardAnyBitmapConverter.html", "classOSXClipboardAnyBitmapConverter" ],
    [ "OSXClipboardAnyTextConverter", "classOSXClipboardAnyTextConverter.html", "classOSXClipboardAnyTextConverter" ],
    [ "OSXClipboardBMPConverter", "classOSXClipboardBMPConverter.html", "classOSXClipboardBMPConverter" ],
    [ "OSXClipboardHTMLConverter", "classOSXClipboardHTMLConverter.html", "classOSXClipboardHTMLConverter" ],
    [ "OSXClipboardTextConverter", "classOSXClipboardTextConverter.html", "classOSXClipboardTextConverter" ],
    [ "OSXClipboardUTF16Converter", "classOSXClipboardUTF16Converter.html", "classOSXClipboardUTF16Converter" ],
    [ "OSXClipboardUTF8Converter", "classOSXClipboardUTF8Converter.html", "classOSXClipboardUTF8Converter" ],
    [ "OSXEventQueueBuffer", "classOSXEventQueueBuffer.html", "classOSXEventQueueBuffer" ],
    [ "OSXKeyState", "classOSXKeyState.html", "classOSXKeyState" ],
    [ "OSXPowerManager", "classOSXPowerManager.html", "classOSXPowerManager" ],
    [ "OSXScreen", "classOSXScreen.html", "classOSXScreen" ],
    [ "OSXScreenSaver", "classOSXScreenSaver.html", "classOSXScreenSaver" ],
    [ "OSXUchrKeyResource", "classOSXUchrKeyResource.html", "classOSXUchrKeyResource" ],
    [ "PacketStreamFilter", "classPacketStreamFilter.html", "classPacketStreamFilter" ],
    [ "PlatformScreen", "classPlatformScreen.html", "classPlatformScreen" ],
    [ "PrimaryClient", "classPrimaryClient.html", "classPrimaryClient" ],
    [ "PriorityQueue", "classPriorityQueue.html", "classPriorityQueue" ],
    [ "ProtocolUtil", "classProtocolUtil.html", "classProtocolUtil" ],
    [ "QSettingsProxy", "classQSettingsProxy.html", "classQSettingsProxy" ],
    [ "Screen", "classScreen.html", "classScreen" ],
    [ "ScreenConfig", "classScreenConfig.html", "classScreenConfig" ],
    [ "ScreenList", "classScreenList.html", "classScreenList" ],
    [ "<ScreenSaverControl>", "protocolScreenSaverControl-p.html", "protocolScreenSaverControl-p" ],
    [ "ScreenSaverController", "interfaceScreenSaverController.html", "interfaceScreenSaverController" ],
    [ "ScreenSettingsDialog", "classScreenSettingsDialog.html", "classScreenSettingsDialog" ],
    [ "ScreenSetupModel", "classScreenSetupModel.html", "classScreenSetupModel" ],
    [ "ScreenSetupView", "classScreenSetupView.html", "classScreenSetupView" ],
    [ "ScrollRemainder", "structScrollRemainder.html", "structScrollRemainder" ],
    [ "SecureListenSocket", "classSecureListenSocket.html", "classSecureListenSocket" ],
    [ "SecureSocket", "classSecureSocket.html", "classSecureSocket" ],
    [ "Server", "classServer.html", "classServer" ],
    [ "ServerApp", "classServerApp.html", "classServerApp" ],
    [ "ServerConfig", "classServerConfig.html", "classServerConfig" ],
    [ "ServerConfigDialog", "classServerConfigDialog.html", "classServerConfigDialog" ],
    [ "ServerProxy", "classServerProxy.html", "classServerProxy" ],
    [ "Settings", "classSettings.html", "classSettings" ],
    [ "SettingsDialog", "classSettingsDialog.html", "classSettingsDialog" ],
    [ "SimpleEventQueueBuffer", "classSimpleEventQueueBuffer.html", "classSimpleEventQueueBuffer" ],
    [ "SocketMultiplexer", "classSocketMultiplexer.html", "classSocketMultiplexer" ],
    [ "Ssl", "structSsl.html", "structSsl" ],
    [ "SslLogger", "classSslLogger.html", "classSslLogger" ],
    [ "StopLogOutputter", "classStopLogOutputter.html", "classStopLogOutputter" ],
    [ "Stopwatch", "classStopwatch.html", "classStopwatch" ],
    [ "StreamBuffer", "classStreamBuffer.html", "classStreamBuffer" ],
    [ "StreamChunker", "classStreamChunker.html", "classStreamChunker" ],
    [ "StreamFilter", "classStreamFilter.html", "classStreamFilter" ],
    [ "SystemLogger", "classSystemLogger.html", "classSystemLogger" ],
    [ "SystemLogOutputter", "classSystemLogOutputter.html", "classSystemLogOutputter" ],
    [ "TCPListenSocket", "classTCPListenSocket.html", "classTCPListenSocket" ],
    [ "TCPSocket", "classTCPSocket.html", "classTCPSocket" ],
    [ "TCPSocketFactory", "classTCPSocketFactory.html", "classTCPSocketFactory" ],
    [ "Thread", "classThread.html", "classThread" ],
    [ "TlsCertificate", "classTlsCertificate.html", "classTlsCertificate" ],
    [ "TMethodJob", "classTMethodJob.html", "classTMethodJob" ],
    [ "TrashScreenWidget", "classTrashScreenWidget.html", "classTrashScreenWidget" ],
    [ "TSocketMultiplexerMethodJob", "classTSocketMultiplexerMethodJob.html", "classTSocketMultiplexerMethodJob" ],
    [ "Unicode", "classUnicode.html", "classUnicode" ],
    [ "VersionChecker", "classVersionChecker.html", "classVersionChecker" ],
    [ "Win32Modifiers", "structWin32Modifiers.html", "structWin32Modifiers" ],
    [ "XArchDaemon", "classXArchDaemon.html", null ],
    [ "XArchDaemonFailed", "classXArchDaemonFailed.html", null ],
    [ "XArchDaemonInstallFailed", "classXArchDaemonInstallFailed.html", null ],
    [ "XArchDaemonUninstallFailed", "classXArchDaemonUninstallFailed.html", null ],
    [ "XArchDaemonUninstallNotInstalled", "classXArchDaemonUninstallNotInstalled.html", null ],
    [ "XArchNetwork", "classXArchNetwork.html", null ],
    [ "XArchNetworkAccess", "classXArchNetworkAccess.html", null ],
    [ "XArchNetworkAddressInUse", "classXArchNetworkAddressInUse.html", null ],
    [ "XArchNetworkConnectionRefused", "classXArchNetworkConnectionRefused.html", null ],
    [ "XArchNetworkDisconnected", "classXArchNetworkDisconnected.html", null ],
    [ "XArchNetworkInterrupted", "classXArchNetworkInterrupted.html", null ],
    [ "XArchNetworkIO", "classXArchNetworkIO.html", null ],
    [ "XArchNetworkName", "classXArchNetworkName.html", null ],
    [ "XArchNetworkNameFailure", "classXArchNetworkNameFailure.html", null ],
    [ "XArchNetworkNameNoAddress", "classXArchNetworkNameNoAddress.html", null ],
    [ "XArchNetworkNameUnavailable", "classXArchNetworkNameUnavailable.html", null ],
    [ "XArchNetworkNameUnknown", "classXArchNetworkNameUnknown.html", null ],
    [ "XArchNetworkNameUnsupported", "classXArchNetworkNameUnsupported.html", null ],
    [ "XArchNetworkNoAddress", "classXArchNetworkNoAddress.html", null ],
    [ "XArchNetworkNoRoute", "classXArchNetworkNoRoute.html", null ],
    [ "XArchNetworkNotConnected", "classXArchNetworkNotConnected.html", null ],
    [ "XArchNetworkResource", "classXArchNetworkResource.html", null ],
    [ "XArchNetworkShutdown", "classXArchNetworkShutdown.html", null ],
    [ "XArchNetworkSupport", "classXArchNetworkSupport.html", null ],
    [ "XArchNetworkTimedOut", "classXArchNetworkTimedOut.html", null ],
    [ "XBadClient", "classXBadClient.html", "classXBadClient" ],
    [ "XBase", "classXBase.html", "classXBase" ],
    [ "XDeskflow", "classXDeskflow.html", null ],
    [ "XDuplicateClient", "classXDuplicateClient.html", "classXDuplicateClient" ],
    [ "XExitApp", "classXExitApp.html", "classXExitApp" ],
    [ "XIncompatibleClient", "classXIncompatibleClient.html", "classXIncompatibleClient" ],
    [ "XInvalidProtocol", "classXInvalidProtocol.html", "classXInvalidProtocol" ],
    [ "XIO", "classXIO.html", null ],
    [ "XIOClose", "classXIOClose.html", null ],
    [ "XIOClosed", "classXIOClosed.html", "classXIOClosed" ],
    [ "XIOEndOfStream", "classXIOEndOfStream.html", "classXIOEndOfStream" ],
    [ "XIOReadMismatch", "classXIOReadMismatch.html", "classXIOReadMismatch" ],
    [ "XIOWouldBlock", "classXIOWouldBlock.html", "classXIOWouldBlock" ],
    [ "XMT", "classXMT.html", null ],
    [ "XMTThreadUnavailable", "classXMTThreadUnavailable.html", "classXMTThreadUnavailable" ],
    [ "XScreen", "classXScreen.html", null ],
    [ "XScreenOpenFailure", "classXScreenOpenFailure.html", "classXScreenOpenFailure" ],
    [ "XScreenUnavailable", "classXScreenUnavailable.html", "classXScreenUnavailable" ],
    [ "XSocket", "classXSocket.html", null ],
    [ "XSocketAddress", "classXSocketAddress.html", "classXSocketAddress" ],
    [ "XSocketAddressInUse", "classXSocketAddressInUse.html", "classXSocketAddressInUse" ],
    [ "XSocketBind", "classXSocketBind.html", "classXSocketBind" ],
    [ "XSocketConnect", "classXSocketConnect.html", "classXSocketConnect" ],
    [ "XSocketCreate", "classXSocketCreate.html", "classXSocketCreate" ],
    [ "XSocketIOClose", "classXSocketIOClose.html", "classXSocketIOClose" ],
    [ "XSocketWithWhat", "classXSocketWithWhat.html", "classXSocketWithWhat" ],
    [ "XThread", "classXThread.html", null ],
    [ "XThreadCancel", "classXThreadCancel.html", null ],
    [ "XThreadExit", "classXThreadExit.html", "classXThreadExit" ],
    [ "XUnknownClient", "classXUnknownClient.html", "classXUnknownClient" ],
    [ "XWindowsClipboard", "classXWindowsClipboard.html", "classXWindowsClipboard" ],
    [ "XWindowsClipboardAnyBitmapConverter", "classXWindowsClipboardAnyBitmapConverter.html", "classXWindowsClipboardAnyBitmapConverter" ],
    [ "XWindowsClipboardBMPConverter", "classXWindowsClipboardBMPConverter.html", "classXWindowsClipboardBMPConverter" ],
    [ "XWindowsClipboardHTMLConverter", "classXWindowsClipboardHTMLConverter.html", "classXWindowsClipboardHTMLConverter" ],
    [ "XWindowsClipboardTextConverter", "classXWindowsClipboardTextConverter.html", "classXWindowsClipboardTextConverter" ],
    [ "XWindowsClipboardUCS2Converter", "classXWindowsClipboardUCS2Converter.html", "classXWindowsClipboardUCS2Converter" ],
    [ "XWindowsClipboardUTF8Converter", "classXWindowsClipboardUTF8Converter.html", "classXWindowsClipboardUTF8Converter" ],
    [ "XWindowsEventQueueBuffer", "classXWindowsEventQueueBuffer.html", "classXWindowsEventQueueBuffer" ],
    [ "XWindowsKeyState", "classXWindowsKeyState.html", "classXWindowsKeyState" ],
    [ "XWindowsPowerManager", "classXWindowsPowerManager.html", "classXWindowsPowerManager" ],
    [ "XWindowsScreen", "classXWindowsScreen.html", "classXWindowsScreen" ],
    [ "XWindowsScreenSaver", "classXWindowsScreenSaver.html", "classXWindowsScreenSaver" ],
    [ "XWindowsUtil", "classXWindowsUtil.html", "classXWindowsUtil" ]
];