var ArchException_8h =
[
    [ "ThreadException", "classThreadException.html", null ],
    [ "ThreadCancelException", "classThreadCancelException.html", null ],
    [ "ArchNetworkException", "classArchNetworkException.html", null ],
    [ "ArchNetworkInterruptedException", "classArchNetworkInterruptedException.html", null ],
    [ "ArchNetworkAccessException", "classArchNetworkAccessException.html", null ],
    [ "ArchNetworkResourceException", "classArchNetworkResourceException.html", null ],
    [ "ArchNetworkSupportException", "classArchNetworkSupportException.html", null ],
    [ "ArchNetworkIOException", "classArchNetworkIOException.html", null ],
    [ "ArchNetworkNoAddressException", "classArchNetworkNoAddressException.html", null ],
    [ "ArchNetworkAddressInUseException", "classArchNetworkAddressInUseException.html", null ],
    [ "ArchNetworkNoRouteException", "classArchNetworkNoRouteException.html", null ],
    [ "ArchNetworkNotConnectedException", "classArchNetworkNotConnectedException.html", null ],
    [ "ArchNetworkShutdownException", "classArchNetworkShutdownException.html", null ],
    [ "ArchNetworkDisconnectedException", "classArchNetworkDisconnectedException.html", null ],
    [ "ArchNetworkConnectionRefusedException", "classArchNetworkConnectionRefusedException.html", null ],
    [ "ArchNetworkTimedOutException", "classArchNetworkTimedOutException.html", null ],
    [ "ArchNetworkNameException", "classArchNetworkNameException.html", null ],
    [ "ArchNetworkNameUnknownException", "classArchNetworkNameUnknownException.html", null ],
    [ "ArchNetworkNameNoAddressException", "classArchNetworkNameNoAddressException.html", null ],
    [ "ArchNetworkNameFailureException", "classArchNetworkNameFailureException.html", null ],
    [ "ArchNetworkNameUnavailableException", "classArchNetworkNameUnavailableException.html", null ],
    [ "ArchNetworkNameUnsupportedException", "classArchNetworkNameUnsupportedException.html", null ],
    [ "ArchDaemonException", "classArchDaemonException.html", null ],
    [ "ArchDaemonFailedException", "classArchDaemonFailedException.html", null ],
    [ "ArchDaemonInstallException", "classArchDaemonInstallException.html", null ],
    [ "ArchDaemonUninstallFailedException", "classArchDaemonUninstallFailedException.html", null ],
    [ "ArchDaemonUninstallNotInstalledException", "classArchDaemonUninstallNotInstalledException.html", null ],
    [ "RETHROW_THREADEXCEPTION", "ArchException_8h.html#a704c9a459d14bad47b4bb217387548b0", null ]
];