git rm AUTHORS
git rm Makefile.am
git rm Makefile.win
git rm NEWS
git rm acinclude.m4
git rm cmd/Makefile.am
git rm cmd/launcher/CAddScreen.cpp
git rm cmd/launcher/CAddScreen.h
git rm cmd/launcher/CAdvancedOptions.cpp
git rm cmd/launcher/CAdvancedOptions.h
git rm cmd/launcher/CAutoStart.cpp
git rm cmd/launcher/CAutoStart.h
git rm cmd/launcher/CGlobalOptions.cpp
git rm cmd/launcher/CGlobalOptions.h
git rm cmd/launcher/CHotkeyOptions.cpp
git rm cmd/launcher/CHotkeyOptions.h
git rm cmd/launcher/CInfo.cpp
git rm cmd/launcher/CInfo.h
git rm cmd/launcher/CScreensLinks.cpp
git rm cmd/launcher/CScreensLinks.h
git rm cmd/launcher/LaunchUtil.cpp
git rm cmd/launcher/LaunchUtil.h
git rm cmd/launcher/Makefile.am
git rm cmd/launcher/Makefile.win
git rm cmd/launcher/launcher.cpp
git rm cmd/launcher/launcher.rc
git rm cmd/launcher/resource.h
git rm cmd/launcher/synergy.ico
git rm cmd/synergyc/CClientTaskBarReceiver.cpp
git rm cmd/synergyc/CClientTaskBarReceiver.h
git rm cmd/synergyc/CMSWindowsClientTaskBarReceiver.cpp
git rm cmd/synergyc/CMSWindowsClientTaskBarReceiver.h
git rm cmd/synergyc/COSXClientTaskBarReceiver.cpp
git rm cmd/synergyc/COSXClientTaskBarReceiver.h
git rm cmd/synergyc/CXWindowsClientTaskBarReceiver.cpp
git rm cmd/synergyc/CXWindowsClientTaskBarReceiver.h
git rm cmd/synergyc/Makefile.am
git rm cmd/synergyc/Makefile.win
git rm cmd/synergyc/resource.h
git rm cmd/synergyc/synergyc.cpp
git rm cmd/synergyc/synergyc.ico
git rm cmd/synergyc/synergyc.rc
git rm cmd/synergyc/tb_error.ico
git rm cmd/synergyc/tb_idle.ico
git rm cmd/synergyc/tb_run.ico
git rm cmd/synergyc/tb_wait.ico
git rm cmd/synergys/CMSWindowsServerTaskBarReceiver.cpp
git rm cmd/synergys/CMSWindowsServerTaskBarReceiver.h
git rm cmd/synergys/COSXServerTaskBarReceiver.cpp
git rm cmd/synergys/COSXServerTaskBarReceiver.h
git rm cmd/synergys/CServerTaskBarReceiver.cpp
git rm cmd/synergys/CServerTaskBarReceiver.h
git rm cmd/synergys/CXWindowsServerTaskBarReceiver.cpp
git rm cmd/synergys/CXWindowsServerTaskBarReceiver.h
git rm cmd/synergys/Makefile.am
git rm cmd/synergys/Makefile.win
git rm cmd/synergys/resource.h
git rm cmd/synergys/synergys.cpp
git rm cmd/synergys/synergys.ico
git rm cmd/synergys/synergys.rc
git rm cmd/synergys/tb_error.ico
git rm cmd/synergys/tb_idle.ico
git rm cmd/synergys/tb_run.ico
git rm cmd/synergys/tb_wait.ico
git rm config/config.guess
git rm config/config.sub
git rm config/depcomp
git rm config/install-sh
git rm config/missing
git rm config/mkinstalldirs
git rm configure.in
git rm dist/Makefile.am
git rm dist/nullsoft/Makefile.am
git rm dist/nullsoft/Makefile.win
git rm dist/nullsoft/dosify.c
git rm dist/nullsoft/synergy.nsi
git rm dist/rpm/Makefile.am
git rm dist/rpm/synergy.spec.in
git rm doc/Makefile.am
git rm doc/PORTING
git rm doc/about.html
git rm doc/authors.html
git rm doc/autostart.html
git rm doc/banner.html
git rm doc/border.html
git rm doc/compiling.html
git rm doc/configuration.html
git rm doc/contact.html
git rm doc/developer.html
git rm doc/doxygen.cfg.in
git rm doc/faq.html
git rm doc/history.html
git rm doc/home.html
git rm doc/images/logo.gif
git rm doc/images/warp.gif
git rm doc/index.html
git rm doc/license.html
git rm doc/news.html
git rm doc/roadmap.html
git rm doc/running.html
git rm doc/security.html
git rm doc/synergy.css
git rm doc/tips.html
git rm doc/toc.html
git rm doc/todo.html
git rm doc/trouble.html
git rm examples/synergy.conf
git rm lib/Makefile.am
git rm lib/arch/CArch.cpp
git rm lib/arch/CArch.h
git rm lib/arch/CArchConsoleUnix.cpp
git rm lib/arch/CArchConsoleUnix.h
git rm lib/arch/CArchConsoleWindows.cpp
git rm lib/arch/CArchConsoleWindows.h
git rm lib/arch/CArchDaemonNone.cpp
git rm lib/arch/CArchDaemonNone.h
git rm lib/arch/CArchDaemonUnix.cpp
git rm lib/arch/CArchDaemonUnix.h
git rm lib/arch/CArchDaemonWindows.cpp
git rm lib/arch/CArchDaemonWindows.h
git rm lib/arch/CArchFileUnix.cpp
git rm lib/arch/CArchFileUnix.h
git rm lib/arch/CArchFileWindows.cpp
git rm lib/arch/CArchFileWindows.h
git rm lib/arch/CArchLogUnix.cpp
git rm lib/arch/CArchLogUnix.h
git rm lib/arch/CArchLogWindows.cpp
git rm lib/arch/CArchLogWindows.h
git rm lib/arch/CArchMiscWindows.cpp
git rm lib/arch/CArchMiscWindows.h
git rm lib/arch/CArchMultithreadPosix.cpp
git rm lib/arch/CArchMultithreadPosix.h
git rm lib/arch/CArchMultithreadWindows.cpp
git rm lib/arch/CArchMultithreadWindows.h
git rm lib/arch/CArchNetworkBSD.cpp
git rm lib/arch/CArchNetworkBSD.h
git rm lib/arch/CArchNetworkWinsock.cpp
git rm lib/arch/CArchNetworkWinsock.h
git rm lib/arch/CArchSleepUnix.cpp
git rm lib/arch/CArchSleepUnix.h
git rm lib/arch/CArchSleepWindows.cpp
git rm lib/arch/CArchSleepWindows.h
git rm lib/arch/CArchStringUnix.cpp
git rm lib/arch/CArchStringUnix.h
git rm lib/arch/CArchStringWindows.cpp
git rm lib/arch/CArchStringWindows.h
git rm lib/arch/CArchSystemUnix.cpp
git rm lib/arch/CArchSystemUnix.h
git rm lib/arch/CArchSystemWindows.cpp
git rm lib/arch/CArchSystemWindows.h
git rm lib/arch/CArchTaskBarWindows.cpp
git rm lib/arch/CArchTaskBarWindows.h
git rm lib/arch/CArchTaskBarXWindows.cpp
git rm lib/arch/CArchTaskBarXWindows.h
git rm lib/arch/CArchTimeUnix.cpp
git rm lib/arch/CArchTimeUnix.h
git rm lib/arch/CArchTimeWindows.cpp
git rm lib/arch/CArchTimeWindows.h
git rm lib/arch/CMultibyte.cpp
git rm lib/arch/IArchConsole.h
git rm lib/arch/IArchDaemon.h
git rm lib/arch/IArchFile.h
git rm lib/arch/IArchLog.h
git rm lib/arch/IArchMultithread.h
git rm lib/arch/IArchNetwork.h
git rm lib/arch/IArchSleep.h
git rm lib/arch/IArchString.h
git rm lib/arch/IArchSystem.h
git rm lib/arch/IArchTaskBar.h
git rm lib/arch/IArchTaskBarReceiver.h
git rm lib/arch/IArchTime.h
git rm lib/arch/Makefile.am
git rm lib/arch/Makefile.win
git rm lib/arch/XArch.cpp
git rm lib/arch/XArch.h
git rm lib/arch/XArchUnix.cpp
git rm lib/arch/XArchUnix.h
git rm lib/arch/XArchWindows.cpp
git rm lib/arch/XArchWindows.h
git rm lib/arch/vsnprintf.cpp
git rm lib/base/CEvent.cpp
git rm lib/base/CEvent.h
git rm lib/base/CEventQueue.cpp
git rm lib/base/CEventQueue.h
git rm lib/base/CFunctionEventJob.cpp
git rm lib/base/CFunctionEventJob.h
git rm lib/base/CFunctionJob.cpp
git rm lib/base/CFunctionJob.h
git rm lib/base/CLog.cpp
git rm lib/base/CLog.h
git rm lib/base/CPriorityQueue.h
git rm lib/base/CSimpleEventQueueBuffer.cpp
git rm lib/base/CSimpleEventQueueBuffer.h
git rm lib/base/CStopwatch.cpp
git rm lib/base/CStopwatch.h
git rm lib/base/CString.h
git rm lib/base/CStringUtil.cpp
git rm lib/base/CStringUtil.h
git rm lib/base/CUnicode.cpp
git rm lib/base/CUnicode.h
git rm lib/base/IEventJob.h
git rm lib/base/IEventQueue.cpp
git rm lib/base/IEventQueue.h
git rm lib/base/IEventQueueBuffer.h
git rm lib/base/IJob.h
git rm lib/base/ILogOutputter.h
git rm lib/base/LogOutputters.cpp
git rm lib/base/LogOutputters.h
git rm lib/base/Makefile.am
git rm lib/base/Makefile.win
git rm lib/base/TMethodEventJob.h
git rm lib/base/TMethodJob.h
git rm lib/base/XBase.cpp
git rm lib/base/XBase.h
git rm lib/client/CClient.cpp
git rm lib/client/CClient.h
git rm lib/client/CServerProxy.cpp
git rm lib/client/CServerProxy.h
git rm lib/client/Makefile.am
git rm lib/client/Makefile.win
git rm lib/common/BasicTypes.h
git rm lib/common/IInterface.h
git rm lib/common/MacOSXPrecomp.h
git rm lib/common/Makefile.am
git rm lib/common/Makefile.win
git rm lib/common/Version.cpp
git rm lib/common/Version.h
git rm lib/common/common.h
git rm lib/common/stdbitset.h
git rm lib/common/stddeque.h
git rm lib/common/stdfstream.h
git rm lib/common/stdistream.h
git rm lib/common/stdlist.h
git rm lib/common/stdmap.h
git rm lib/common/stdostream.h
git rm lib/common/stdpost.h
git rm lib/common/stdpre.h
git rm lib/common/stdset.h
git rm lib/common/stdsstream.h
git rm lib/common/stdstring.h
git rm lib/common/stdvector.h
git rm lib/io/CStreamBuffer.cpp
git rm lib/io/CStreamBuffer.h
git rm lib/io/CStreamFilter.cpp
git rm lib/io/CStreamFilter.h
git rm lib/io/IStream.cpp
git rm lib/io/IStream.h
git rm lib/io/IStreamFilterFactory.h
git rm lib/io/Makefile.am
git rm lib/io/Makefile.win
git rm lib/io/XIO.cpp
git rm lib/io/XIO.h
git rm lib/mt/CCondVar.cpp
git rm lib/mt/CCondVar.h
git rm lib/mt/CLock.cpp
git rm lib/mt/CLock.h
git rm lib/mt/CMutex.cpp
git rm lib/mt/CMutex.h
git rm lib/mt/CThread.cpp
git rm lib/mt/CThread.h
git rm lib/mt/Makefile.am
git rm lib/mt/Makefile.win
git rm lib/mt/XMT.cpp
git rm lib/mt/XMT.h
git rm lib/mt/XThread.h
git rm lib/net/CNetworkAddress.cpp
git rm lib/net/CNetworkAddress.h
git rm lib/net/CSocketMultiplexer.cpp
git rm lib/net/CSocketMultiplexer.h
git rm lib/net/CTCPListenSocket.cpp
git rm lib/net/CTCPListenSocket.h
git rm lib/net/CTCPSocket.cpp
git rm lib/net/CTCPSocket.h
git rm lib/net/CTCPSocketFactory.cpp
git rm lib/net/CTCPSocketFactory.h
git rm lib/net/IDataSocket.cpp
git rm lib/net/IDataSocket.h
git rm lib/net/IListenSocket.cpp
git rm lib/net/IListenSocket.h
git rm lib/net/ISocket.cpp
git rm lib/net/ISocket.h
git rm lib/net/ISocketFactory.h
git rm lib/net/ISocketMultiplexerJob.h
git rm lib/net/Makefile.am
git rm lib/net/Makefile.win
git rm lib/net/TSocketMultiplexerMethodJob.h
git rm lib/net/XSocket.cpp
git rm lib/net/XSocket.h
git rm lib/platform/CMSWindowsClipboard.cpp
git rm lib/platform/CMSWindowsClipboard.h
git rm lib/platform/CMSWindowsClipboardAnyTextConverter.cpp
git rm lib/platform/CMSWindowsClipboardAnyTextConverter.h
git rm lib/platform/CMSWindowsClipboardBitmapConverter.cpp
git rm lib/platform/CMSWindowsClipboardBitmapConverter.h
git rm lib/platform/CMSWindowsClipboardHTMLConverter.cpp
git rm lib/platform/CMSWindowsClipboardHTMLConverter.h
git rm lib/platform/CMSWindowsClipboardTextConverter.cpp
git rm lib/platform/CMSWindowsClipboardTextConverter.h
git rm lib/platform/CMSWindowsClipboardUTF16Converter.cpp
git rm lib/platform/CMSWindowsClipboardUTF16Converter.h
git rm lib/platform/CMSWindowsDesks.cpp
git rm lib/platform/CMSWindowsDesks.h
git rm lib/platform/CMSWindowsEventQueueBuffer.cpp
git rm lib/platform/CMSWindowsEventQueueBuffer.h
git rm lib/platform/CMSWindowsKeyState.cpp
git rm lib/platform/CMSWindowsKeyState.h
git rm lib/platform/CMSWindowsScreen.cpp
git rm lib/platform/CMSWindowsScreen.h
git rm lib/platform/CMSWindowsScreenSaver.cpp
git rm lib/platform/CMSWindowsScreenSaver.h
git rm lib/platform/CMSWindowsUtil.cpp
git rm lib/platform/CMSWindowsUtil.h
git rm lib/platform/COSXClipboard.cpp
git rm lib/platform/COSXClipboard.h
git rm lib/platform/COSXClipboardAnyTextConverter.cpp
git rm lib/platform/COSXClipboardAnyTextConverter.h
git rm lib/platform/COSXClipboardTextConverter.cpp
git rm lib/platform/COSXClipboardTextConverter.h
git rm lib/platform/COSXClipboardUTF16Converter.cpp
git rm lib/platform/COSXClipboardUTF16Converter.h
git rm lib/platform/COSXEventQueueBuffer.cpp
git rm lib/platform/COSXEventQueueBuffer.h
git rm lib/platform/COSXKeyState.cpp
git rm lib/platform/COSXKeyState.h
git rm lib/platform/COSXScreen.cpp
git rm lib/platform/COSXScreen.h
git rm lib/platform/COSXScreenSaver.cpp
git rm lib/platform/COSXScreenSaver.h
git rm lib/platform/COSXScreenSaverUtil.h
git rm lib/platform/COSXScreenSaverUtil.m
git rm lib/platform/CSynergyHook.cpp
git rm lib/platform/CSynergyHook.h
git rm lib/platform/CXWindowsClipboard.cpp
git rm lib/platform/CXWindowsClipboard.h
git rm lib/platform/CXWindowsClipboardAnyBitmapConverter.cpp
git rm lib/platform/CXWindowsClipboardAnyBitmapConverter.h
git rm lib/platform/CXWindowsClipboardBMPConverter.cpp
git rm lib/platform/CXWindowsClipboardBMPConverter.h
git rm lib/platform/CXWindowsClipboardHTMLConverter.cpp
git rm lib/platform/CXWindowsClipboardHTMLConverter.h
git rm lib/platform/CXWindowsClipboardTextConverter.cpp
git rm lib/platform/CXWindowsClipboardTextConverter.h
git rm lib/platform/CXWindowsClipboardUCS2Converter.cpp
git rm lib/platform/CXWindowsClipboardUCS2Converter.h
git rm lib/platform/CXWindowsClipboardUTF8Converter.cpp
git rm lib/platform/CXWindowsClipboardUTF8Converter.h
git rm lib/platform/CXWindowsEventQueueBuffer.cpp
git rm lib/platform/CXWindowsEventQueueBuffer.h
git rm lib/platform/CXWindowsKeyState.cpp
git rm lib/platform/CXWindowsKeyState.h
git rm lib/platform/CXWindowsScreen.cpp
git rm lib/platform/CXWindowsScreen.h
git rm lib/platform/CXWindowsScreenSaver.cpp
git rm lib/platform/CXWindowsScreenSaver.h
git rm lib/platform/CXWindowsUtil.cpp
git rm lib/platform/CXWindowsUtil.h
git rm lib/platform/Makefile.am
git rm lib/platform/Makefile.win
git rm lib/platform/OSXScreenSaverControl.h
git rm lib/server/CBaseClientProxy.cpp
git rm lib/server/CBaseClientProxy.h
git rm lib/server/CClientListener.cpp
git rm lib/server/CClientListener.h
git rm lib/server/CClientProxy.cpp
git rm lib/server/CClientProxy.h
git rm lib/server/CClientProxy1_0.cpp
git rm lib/server/CClientProxy1_0.h
git rm lib/server/CClientProxy1_1.cpp
git rm lib/server/CClientProxy1_1.h
git rm lib/server/CClientProxy1_2.cpp
git rm lib/server/CClientProxy1_2.h
git rm lib/server/CClientProxy1_3.cpp
git rm lib/server/CClientProxy1_3.h
git rm lib/server/CClientProxyUnknown.cpp
git rm lib/server/CClientProxyUnknown.h
git rm lib/server/CConfig.cpp
git rm lib/server/CConfig.h
git rm lib/server/CInputFilter.cpp
git rm lib/server/CInputFilter.h
git rm lib/server/CPrimaryClient.cpp
git rm lib/server/CPrimaryClient.h
git rm lib/server/CServer.cpp
git rm lib/server/CServer.h
git rm lib/server/Makefile.am
git rm lib/server/Makefile.win
git rm lib/synergy/CClipboard.cpp
git rm lib/synergy/CClipboard.h
git rm lib/synergy/CKeyMap.cpp
git rm lib/synergy/CKeyMap.h
git rm lib/synergy/CKeyState.cpp
git rm lib/synergy/CKeyState.h
git rm lib/synergy/CPacketStreamFilter.cpp
git rm lib/synergy/CPacketStreamFilter.h
git rm lib/synergy/CPlatformScreen.cpp
git rm lib/synergy/CPlatformScreen.h
git rm lib/synergy/CProtocolUtil.cpp
git rm lib/synergy/CProtocolUtil.h
git rm lib/synergy/CScreen.cpp
git rm lib/synergy/CScreen.h
git rm lib/synergy/ClipboardTypes.h
git rm lib/synergy/IClient.h
git rm lib/synergy/IClipboard.cpp
git rm lib/synergy/IClipboard.h
git rm lib/synergy/IKeyState.cpp
git rm lib/synergy/IKeyState.h
git rm lib/synergy/IPlatformScreen.h
git rm lib/synergy/IPrimaryScreen.cpp
git rm lib/synergy/IPrimaryScreen.h
git rm lib/synergy/IScreen.cpp
git rm lib/synergy/IScreen.h
git rm lib/synergy/IScreenSaver.h
git rm lib/synergy/ISecondaryScreen.h
git rm lib/synergy/KeyTypes.cpp
git rm lib/synergy/KeyTypes.h
git rm lib/synergy/Makefile.am
git rm lib/synergy/Makefile.win
git rm lib/synergy/MouseTypes.h
git rm lib/synergy/OptionTypes.h
git rm lib/synergy/ProtocolTypes.cpp
git rm lib/synergy/ProtocolTypes.h
git rm lib/synergy/XScreen.cpp
git rm lib/synergy/XScreen.h
git rm lib/synergy/XSynergy.cpp
git rm lib/synergy/XSynergy.h
git rm win32util/autodep.cpp