SET(CMAKE_SHARED_LIBRARY_PREFIX "lib")
SET(CMAKE_SHARED_LIBRARY_SUFFIX ".dll")
SET(CMAKE_SHARED_LIBRARY_Fortran_FLAGS "") 
SET(CMAKE_SHARED_LIBRARY_Fortran_FLAGS "")
SET(CMAKE_EXECUTABLE_SUFFIX ".exe")          # .exe
INCLUDE(Platform/g77)
