SET(CMAKE_Fortran_MODDIR_FLAG -J)
SET (CMAKE_SHARED_LIBRARY_Fortran_FLAGS "-fPIC")     # -pic
SET (CMAKE_Fortran_FLAGS_INIT "")
SET (CMAKE_Fortran_FLAGS_DEBUG_INIT "-g")
SET (CMAKE_Fortran_FLAGS_MINSIZEREL_INIT "-Os")
SET (CMAKE_Fortran_FLAGS_RELEASE_INIT "-O3")
SET (CMAKE_Fortran_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")

IF(NOT APPLE)
  SET (CMAKE_INCLUDE_SYSTEM_FLAG_Fortran "-isystem ")
ENDIF(NOT APPLE)

# These will require updates to CMake C++ code to support
# preprocessing rules for Fortran.
#SET (CMAKE_Fortran_CREATE_PREPROCESSED_SOURCE "<CMAKE_Fortran_COMPILER> <DEFINES> <FLAGS> -E <SOURCE> > <PREPROCESSED_SOURCE>")
#SET (CMAKE_Fortran_CREATE_ASSEMBLY_SOURCE "<CMAKE_Fortran_COMPILER> <DEFINES> <FLAGS> -S <SOURCE> -o <ASSEMBLY_SOURCE>")
