name: Bug report
description: If you find a bug in Deskflow, please let us know so we can fix it.
type: "Triage [bug]"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve Deskflow.

  - type: checkboxes
    id: sanity-checks
    attributes:
      label: Sanity checks
      description: |
        Before reporting a bug, please first:
        1. Try the latest [continuous build](https://github.com/deskflow/deskflow/releases).
        2. Wayland users, please review the [known issues](https://github.com/deskflow/deskflow/discussions/7499).
        3. macOS users, if the app crashes, try [Apple's solution](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unknown-developer-mh40616/mac).
      options:
        - label: I have done the sanity checks, and my issue persists
        - label: These sanity checks are not relevant to the bug
    validations:
      required: true
      
  - type: textarea
    id: version
    attributes:
      label: Deskflow version info
      description: You can find the Deskflow version number on the About screen.
      placeholder: |
        Deskflow: 1.2.3.4 (deadc0de)
        Qt: 3.2.1
        System: Hannah Montana Linux (Workstation Edition)
        Session: Unity (Compiz)
    validations:
      required: true

  - type: dropdown
    id: build
    attributes:
      label: Build type
      description: What kind of build are you using?
      options:
        # Empty option to force selection
        -
        - Deskflow package (downloaded from Deskflow)
        - Community package (apt, dnf, brew, etc.)
        - Local developer build (built it myself)
        - Other (please specify)
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: os
    attributes:
      label: Operating systems (OS)
      description: Operating systems (OS) in use for all servers and clients
      options:
        - label: Windows
        - label: macOS
        - label: Linux (X11)
        - label: Linux (Wayland)
        - label: BSD-derived
        - label: Other (please specify)
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Deskflow configuration
      description: |
        Please provide a very brief description of your configuration.
        Let us know what OS your server and client are running, including all OS versions.
        If you're using Linux, please provide the name of the distribution.
      placeholder: |
        - Windows 11 server, macOS 15 client
        - Each computer has a single monitor
        - Windows is on the left, macOS is on the right
    validations:
      required: true
      
  - type: textarea
    id: repro-steps
    attributes:
      label: What steps will reproduce the problem?
      description: |
        Please list the _numbered steps_ to reproduce the issue.
        If you're not sure, please provide as much detail as possible.
      placeholder: |
        1. Start Deskflow
        2. Click 'Configure Server'
        3. Click 'Apply'

  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: |
        Please copy and paste any relevant log output. 
        This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: |
        Please provide any additional information that may help us understand the issue.
        This could include screenshots, error messages, or anything else you think is relevant.
        - Any ideas about what maybe causing the problem?
        - Any workarounds that you've discovered?
        - What other apps are you running?
        - Does the issue stop you using Deskflow entirely?
        - Did restarting Deskflow or the computer help?
        - Anything else you can think of?
