gettext("Download");
gettext("<b>Latest release:</b> 1.4.7 Beta (Feb 5, 2012)");
gettext("Please use version 1.4 for easier setup. Use version 1.3 if you experience problems.");
gettext("Source code");
gettext("Previous 1.4 releases");
gettext("Previous 1.3 releases");
gettext("Other projects");
gettext("Related sites");
gettext("Nightly builds");
gettext("use at your own risk");
gettext("Synergy lets you easily share your mouse and keyboard between multiple computers on your desk, and it's Free and Open Source. Just move your mouse off the edge of one computer's screen on to another. You can even share all of your clipboards. All you need is a network connection. Synergy is cross-platform (works on Windows, Mac OS X and Linux).");
gettext("More Info");
gettext("News");
gettext("Blog");
gettext("FAQs");
gettext("User");
gettext("Developer");
gettext("Mailing lists");
gettext("Developer");
gettext("Nightly build");
gettext("Console");
gettext("Builders");
gettext("Packages");
gettext("Key People");
gettext("Project leader and primary developer");
gettext("Original author and project founder");
gettext("Founder of Synergy+ (fork project)");
gettext("Support us!");
gettext("Please help us out by donating or buying merchandise. Thanks for your support!");
gettext("Synergy lets you share your keyboard and mouse between multiple computers on your desk.");
gettext("Home");
gettext("Download");
gettext("Info");
gettext("Support");
gettext("Search");
gettext("Tracker");
gettext("Search");
gettext("Search all Synergy websites from one page.");
gettext("What is searched?");
gettext("Super User");
gettext("Issue tracker");
gettext("Website wiki");
gettext("Mailing lists");
gettext("Search tips");
gettext("If you get too many results, try specifying your operating system.");
gettext("Sometimes issues are specific to the client or server.");
gettext("You may find that entering your version number helps.");
gettext("If this does not work, use the <a href=\"http://www.google.co.uk/cse/home?cx=006438721074957994428:rnklqbsknvs\">alternative Synergy search</a>.");
gettext("Engage!");
gettext("Support");
gettext("Having problems using Synergy? You're in the right place!");
gettext("Do your research");
gettext("Before asking anyone for help, do a <a href=\"/search/\">quick search</a>, it really won't take long. You <strong>must</strong> fully research your problem before asking us for help. You can also <a href=\"/tracker/projects/synergy/wiki/Docs\">read the docs</a> to find out how to use config files, etc.");
gettext("Ask your question");
gettext("If you're having trouble configuring or starting Synergy, please  ask a <strong>question</strong> on the  <a href=\"http://synergy-foss.org/osqa/\">Synergy Q&#38;A site</a>. Read the <a href=\"/osqa/faq/\">FAQ</a> to make sure your question does not get closed.");
gettext("Mailing list and IRC");
gettext("More traditional open source users may prefer to  <a href=\"http://groups.google.com/group/synergy-plus/post\">use the mailing list</a> (just click \"Apply for group membership\" -- everyone is allowed, this is just to protect us against spammers). Please do not post bugs on the mailing list. You can also join our IRC channel: <code>#synergy on irc.freenode.net:8001</code> (for IRC, you could use <a href=\"http://xchat.org/\">XChat</a>) -- but the same applies for IRC; do your research first!");
gettext("Super User");
gettext("If you're familiar with Super User, there's a <a href=\"http://superuser.com/questions/tagged/synergy\">synergy tag</a>.");
gettext("Super User is <b>not</b> dedicated to supporting Synergy.");
gettext("Ask questions; do not nag or comment on bugs or issues.");
gettext("Do not raise new bugs there; use the issue tracker for this.");
gettext("Synergy developers do <i>not</i> monitor this website.");
gettext("Always use the \"synergy\" tag on your question.");
gettext("Make sure you mention \"Synergy\" in the question.");
gettext("Report a bug");
gettext("If you've exhausted all other options (or if you think your issue is really a <b>bug</b>), you can <a href=\"/tracker/account/register\">register</a> a new account <em>and then</em> open a <a href=\"/tracker/projects/synergy/support/new\">new bug report</a> on our issue tracker.");
