IF(CMAKE_SYSTEM MATCHES "MP-RAS-02*.")
  SET(CMAKE_SHARED_LIBRARY_C_FLAGS "-K PIC")
ELSE(CMAKE_SYSTEM MATCHES "MP-RAS-02*.")
  SET(CMAKE_SHARED_LIBRARY_C_FLAGS "-K PIC")
  SET(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "-Wl,-Bexport")
ENDIF(CMAKE_SYSTEM MATCHES "MP-RAS-02*.")

INCLUDE(Platform/UnixPaths)


