INCLUDE("${CMAKE_PLATFORM_ROOT_BIN}/CMakeIntelInformation.cmake" OPTIONAL)

IF(NOT _INTEL_XILINK_TEST_RUN)
  EXECUTE_PROCESS(COMMAND xilink /? 
    ERROR_VARIABLE _XILINK_ERR
    OUTPUT_VARIABLE _XILINK_HELP)
  IF(_XILINK_HELP MATCHES MANIFEST)
    SET(_INTEL_COMPILER_SUPPORTS_MANIFEST 1)
  ENDIF(_XILINK_HELP MATCHES MANIFEST)
  IF(NOT  EXISTS "${CMAKE_PLATFORM_ROOT_BIN}/CMakeIntelInformation.cmake")
    FILE(WRITE ${CMAKE_PLATFORM_ROOT_BIN}/CMakeIntelInformation.cmake 
      "
SET(_INTEL_XILINK_TEST_RUN 1)
SET(_INTEL_COMPILER_SUPPORTS_MANIFEST ${_INTEL_COMPILER_SUPPORTS_MANIFEST})
")
  ENDIF(NOT  EXISTS "${CMAKE_PLATFORM_ROOT_BIN}/CMakeIntelInformation.cmake")
ENDIF(NOT _INTEL_XILINK_TEST_RUN)
