INCLUDE(Platform/Linux-Intel)
IF(XIAR)
  # INTERPROCEDURAL_OPTIMIZATION
  SET(CMAKE_CXX_COMPILE_OPTIONS_IPO -ipo)
  SET(CMAKE_CXX_CREATE_STATIC_LIBRARY_IPO
    "${XIAR} cr <TARGET> <LINK_FLAGS> <OBJECTS> "
    "${XIAR} -s <TARGET> ")
ENDIF(XIAR)
