name: "Run tests"
description: "Runs both unit tests and integration tests and appends to a PR comment"

inputs:
  job:
    description: "The job name to append to the PR comment"
    default: "unknown"

runs:
  using: "composite"

  steps:
    - name: Unit tests
      id: unittests
      env:
        QT_QPA_PLATFORM: offscreen
      run: |
        ./build/bin/unittests
        result=$?

        if [ $result -ne 0 ]; then
          echo "Unit tests failed with code: $result" >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash
      continue-on-error: true

    - name: Integration tests
      id: integtests
      env:
        QT_QPA_PLATFORM: offscreen
      run: |
        ./build/bin/integtests
        result=$?

        if [ $result -ne 0 ]; then
          echo "Integration tests failed with code: $result" >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash
      continue-on-error: true

    - name: Get test results
      id: results
      run: |
        pass="✅ Pass"
        fail="❌ Fail"
        unittests_outcome="${{ steps.unittests.outcome }}"
        integtests_outcome="${{ steps.integtests.outcome }}"
        unittests=$( [ "$unittests_outcome" = "success" ] && echo $pass || echo $fail )
        integtests=$( [ "$integtests_outcome" = "success" ] && echo $pass || echo $fail )
        echo "unittests=$unittests" >> $GITHUB_OUTPUT
        echo "integtests=$integtests" >> $GITHUB_OUTPUT
      shell: bash

    - name: Summary row
      id: row
      run: |
        file="row-${{ inputs.job }}.md"

        row=""
        row+="| ${{ inputs.job }} "
        row+="| ${{ steps.results.outputs.unittests }} "
        row+="| ${{ steps.results.outputs.integtests }} |"
        echo "$row" > $file

        echo "file=$file" > $GITHUB_OUTPUT
      shell: bash

    - name: Save summary row
      uses: actions/upload-artifact@v4
      with:
        name: test-result-${{ inputs.job }}
        path: ${{ steps.row.outputs.file }}

    - name: Check test outcome
      if: steps.unittests.outcome == 'failure'
      run: |
        echo "Unit tests failed"
        exit 1
      shell: bash
