if (UNIX)
    set (CPACK_PACKAGE_VERSION_MAJOR ${BARRIER_VERSION_MAJOR})
    set (CPACK_PACKAGE_VERSION_MINOR ${BARRIER_VERSION_MINOR})
    set (CPACK_PACKAGE_VERSION_PATCH ${BARRIER_VERSION_PATCH})
    set (CPACK_GENERATOR "TBZ2")
    set (CPACK_SOURCE_GENERATOR "TXZ")
    set (CPACK_SOURCE_IGNORE_FILES "/build/;\.gitignore$;/\.git/;/.github/;\.swp$;build_env\.*")
    include (CPack)
endif()
